### ISSUE TITLE
Step #11 shows Success - but nothing happens

### ISSUE THREAD

**Issue by bmw-bharm** [kentrikos/jenkins-bootstrap-pipelines#15]
After following all steps from *11, the job runs successful for 62 ms but nothing happens. Console output:Started by user admin Running in Durability level: MAX_SURVIVABILITY [Pipeline] End of Pipeline Finished: SUCCESS
Parameters of Jenkins job: string(name: 'PRODUCT_DOMAIN_NAME', defaultValue: 'mrt7-trial,') string(name: 'ENVIRONMENT_TYPE', defaultValue: 'dev') string(name: 'CONFIG_REPO_URL', defaultValue: 'ssh://git@github.com/user/k8s-environment-config.git') string(name: 'CONFIG_REPO_DIR', defaultValue: 'application') string(name: 'AWS_ACCOUNT_NUMBER', defaultValue: '012345678910') string(name: 'AWS_REGION', defaultValue: 'us-west-1')

**Comment by mzawadzk** [comment]
Can we close it as outdated?

**Comment by henrikandersson-bmw** [comment]
closed as outdated
