### ISSUE TITLE
Kubernetes cluster is not created from Jenkins core-infra

### ISSUE THREAD

**Issue by mrtsmit** [kentrikos/jenkins-bootstrap-pipelines#16]
Following aws-bootstrap/docs/how-to-start.md steps, on step 9, k8s should be deployed in transit/operations account.  

the script runs for over an hour without results with these repeated messages:

[0m[0mmodule.operations.module.kubernetes_cluster_operations.null_resource.kubernetes_cluster (local-exec): error: the server doesn't have a resource type "nodes"
[0m[0mmodule.operations.module.kubernetes_cluster_operations.null_resource.kubernetes_cluster (local-exec): error: the server doesn't have a resource type "nodes"
module.operations.kubernetes_cluster_operations.null_resource.kubernetes_cluster: Still creating... (1h13m11s elapsed)[0m
module.operations.kubernetes_cluster_operations.null_resource.kubernetes_cluster: Still creating... (1h13m21s elapsed)[0m
module.operations.kubernetes_cluster_operations.null_resource.kubernetes_cluster: Still creating... (1h13m31s elapsed)[0m
[0m[0mmodule.operations.module.kubernetes_cluster_operations.null_resource.kubernetes_cluster (local-exec): error: the server doesn't have a resource type "nodes"
[0m[0mmodule.operations.module.kubernetes_cluster_operations.null_resource.kubernetes_cluster (local-exec): error: the server doesn't have a resource type "nodes"
module.operations.kubernetes_cluster_operations.null_resource.kubernetes_cluster: Still creating... (1h13m41s elapsed)[0m
module.operations.kubernetes_cluster_operations.null_resource.kubernetes_cluster: Still creating... (1h13m51s elapsed)[0m

Details are available in related Jira ticket.

**Comment by mzawadzk** [comment]
Can we close it as outdated?

**Comment by henrikandersson-bmw** [comment]
closed as outdated
