### ISSUE TITLE
[LMA] Deploy Prometheus in Operations Account

### ISSUE THREAD

**Issue by ppolkampalli** [kentrikos/jenkins-bootstrap-pipelines#40]
When I kickoff the job I am getting the following error. 

+ helm upgrade prometheus-ops stable/prometheus --install -wait --namespace lma '--set=server.ingress.enabled=true,server.ingress.hosts={prometheus.xxx}' --set=alertmanager.enabled=true --set=alertmanager.ingress.enabled=true '--set=alertmanager.ingress.hosts={xxxxx}' -f ./prometheus/alertmanager.yml

Error: unknown shorthand flag: 'w' in –wait

Looks like we are missing -- at wait .

**Comment by henrikandersson-bmw** [comment]
Fixed for operations/prometheus and applications/prometheus deployments in new Release 0.10.0.

[Release 0.10.0](https://github.com/kentrikos/jenkins-bootstrap-pipelines/releases/tag/0.10.0)

**Comment by henrikandersson-bmw** [comment]
Fixed for operations/prometheus and applications/prometheus deployments in new Release 0.10.0.

[Release 0.10.0](https://github.com/kentrikos/jenkins-bootstrap-pipelines/releases/tag/0.10.0)
